#include "SamgrApiTest.h"
#include "gtest/gtest.h"
#include "log.h"
#include <unistd.h>
#include <cstdio>
#include <csignal>
#include <feature.h>
#include <hos_init.h>
#include <samgr_lite.h>
#include <securec.h>
