#include "common/image.h"
#include "components/ui_slider.h"
#include "draw/draw_image.h"
#include "draw/draw_rect.h"
#include "graphic_log.h"
#include "imgdecode/cache_manager.h"
#include "themes/theme_manager.h"
