#include "key_parser.h"
#include <string.h>
#include "acelite_config.h"
#include "js_config.h"
#include "keys.h"
#ifdef KEYWORD
#undef KEYWORD
#endif // KEYWORD
#if defined(ENABLE_KEY)
#define KEYWORD(enumkey, keystr) {#keystr, K_##enumkey, static_cast<uint8_t>(strlen(#enumkey))},
#else // ENABLE_KEY
#define KEYWORD(enumkey, keystr) {K_##enumkey, static_cast<uint8_t>(strlen(#enumkey))},
#endif // ENABLE_KEY
#if defined(ENABLE_KEY)
#endif
#if defined(ENABLE_KEY)
#else  // ENABLE_KEY
#endif // ENABLE_KEY
#ifdef OHOS_ACELITE_KEYS_H
#undef OHOS_ACELITE_KEYS_H
#include "keys.h"
#endif // OHOS_ACELITE_KEYS_H
#undef KEYWORD
#ifdef FEATURE_COMPONENT_ANALOG_CLOCK
#endif // FEATURE_COMPONENT_ANALOG_CLOCK
#ifdef FEATURE_COMPONENT_VIDEO
#endif // FEATURE_COMPONENT_VIDEO
#ifdef FEATURE_COMPONENT_CAMERA
#endif // FEATURE_COMPONENT_CAMERA
#ifdef FEATURE_COMPONENT_CANVAS
#endif // FEATURE_COMPONENT_CANVAS
#ifdef FEATURE_COMPONENT_VIDEO
#endif // FEATURE_COMPONENT_VIDEO
#ifdef FEATURE_COMPONENT_ANALOG_CLOCK
#endif // FEATURE_COMPONENT_ANALOG_CLOCK
#ifdef FEATURE_COMPONENT_DATE_PICKER
#endif // FEATURE_COMPONENT_DATE_PICKER
#ifdef FEATURE_COMPONENT_DATE_PICKER
#endif // FEATURE_COMPONENT_DATE_PICKER
#if (defined(FEATURE_COMPONENT_CAMERA) || defined(FEATURE_COMPONENT_VIDEO))
#endif // defined(FEATURE_COMPONENT_CAMERA) || defined(FEATURE_COMPONENT_VIDEO)
#ifdef FEATURE_COMPONENT_VIDEO
#endif // FEATURE_COMPONENT_VIDEO
#ifdef FEATURE_COMPONENT_ANALOG_CLOCK
#endif // FEATURE_COMPONENT_ANALOG_CLOCK
#ifdef JS_TOUCH_EVENT_SUPPORT
#endif
#ifdef FEATURE_COMPONENT_VIDEO
#endif // FEATURE_COMPONENT_VIDEO
#ifdef FEATURE_COMPONENT_VIDEO
#endif // FEATURE_COMPONENT_VIDEO
#ifdef FEATURE_COMPONENT_ANALOG_CLOCK
#endif // FEATURE_COMPONENT_ANALOG_CLOCK
#ifdef FEATURE_COMPONENT_VIDEO
#endif // FEATURE_COMPONENT_VIDEO
#ifdef FEATURE_COMPONENT_ANALOG_CLOCK
#endif // FEATURE_COMPONENT_ANALOG_CLOCK
#ifdef FEATURE_COMPONENT_VIDEO
#endif // FEATURE_COMPONENT_VIDEO
#if (defined(FEATURE_COMPONENT_DATE_PICKER) || defined(FEATURE_COMPONENT_VIDEO))
#endif // (defined(FEATURE_COMPONENT_DATE_PICKER) || defined(FEATURE_COMPONENT_VIDEO)
#ifdef FEATURE_COMPONENT_TABS
#endif // FEATURE_COMPONENT_TABS
#ifdef FEATURE_COMPONENT_VIDEO
#endif // FEATURE_COMPONENT_VIDEO
#ifdef JS_TOUCH_EVENT_SUPPORT
#endif
#ifdef FEATURE_COMPONENT_ANALOG_CLOCK
#endif // FEATURE_COMPONENT_ANALOG_CLOCK
#ifdef FEATURE_COMPONENT_VIDEO
#endif // FEATURE_COMPONENT_VIDEO
#if defined(ENABLE_KEY)
#else
#endif // ENABLE_KEY
