#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <inttypes.h>
#include <time.h>
#include <unistd.h>
#include <sched.h>
#include <sys/time.h>
#include <sys/resource.h>
#include <math.h>
#include "gtest/gtest.h"
#include "XtsActsUtil.h"
#include "XtsActsMathApiExpect.h"
